version: "3"

services:
  springapp:
    build: .
    container_name: springapp
    ports:
      - "80:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logs_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: logs_db

    ports:
      - "5432:5432"

